# NF7-DO-03

name: Conventional Commits

on:
  push:
    branches:
      - feature/**
      - hotfix/**

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.3.0