# NF8-DO-04

name: Merge PRs
on:
  pull_request:
    types:
      - closed
jobs:
  delete_branch_feature:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature/') && github.base_ref == 'develop' 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Suppression de la branche feature
        run: git push origin --delete ${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  delete_branch_hotfix:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'hotfix/') && github.base_ref == 'main' 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Suppression de la branche hotfix
        run: git push origin --delete ${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"